version: "3.9"

services:
  frontend:
    container_name: foodpick-frontend
    build:
      context: .
      dockerfile: scaffold/Dockerfile
    volumes:
      - ./foodpick-nextjs-front:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
