version: "3.9"

services:
  frontend:
    container_name: foodpick-frontend
    build:
      context: .
      dockerfile: scaffold/Dockerfile
    volumes:
      - ./foodpick-nextjs-front:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_BACKEND_URL=http://foodpick-api:3000 # <--- 가장 중요! 또는 http://api:3000
      - NEXT_PUBLIC_API_BASE_PATH=/api # 클라이언트 사이드에서 API 호출 시 사용할 기본 경로 (선택적)
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - foodpick-network

networks:
  foodpick-network:
    external: true
